docs/design/message-visibility-timeout-handling.md, src/AWS.Messaging/Configuration/MessageBusBuilder.cs, src/AWS.Messaging/Configuration/MessageManagerConfiguration.cs, src/AWS.Messaging/Configuration/SQSMessagePollerConfiguration.cs, src/AWS.Messaging/Configuration/SQSMessagePollerOptions.cs, src/AWS.Messaging/MessageEnvelope.cs, src/AWS.Messaging/SQS/SQSMessagePoller.cs, src/AWS.Messaging/Services/DefaultMessageManager.cs, src/AWS.Messaging/Services/IMessageManagerFactory.cs, src/AWS.Messaging/Services/IMessagePoller.cs, src/AWS.Messaging/Services/InFlightMetadata.cs, test/AWS.Messaging.IntegrationTests/Models/ChatMessage.cs, test/AWS.Messaging.IntegrationTests/SubscriberTests.cs, test/AWS.Messaging.UnitTests/DefaultMessageManagerTests.cs, test/AWS.Messaging.UnitTests/MessageBusBuilderTests.cs, test/AWS.Messaging.UnitTests/SQSMessagePollerTests.cs
*Issue #, if available:* DOTNET-6901
*Description of changes:* Adds a design doc for the SQS poller will manage the visibility timeout for messages that are still being handled.
* This is discussed briefly in the overall design, but here's more detail. I imagine pieces of this can be reused for the documentation later.
* A rudimentary version of this is currently implemented in `main`/`dev` (all in flight messages are extended). A code change will follow this PR with updates to the configuration options and batching behavior.
See the two open questions at the end, thanks.
=> docs: Add design for how the SQS poller will handle message visibility timeout for in flight messages

docs/design/message-source-computation-design.md, src/AWS.Messaging/AWS.Messaging.csproj, src/AWS.Messaging/Configuration/IMessageBusBuilder.cs, src/AWS.Messaging/Configuration/IMessageConfiguration.cs, src/AWS.Messaging/Configuration/MessageBusBuilder.cs, src/AWS.Messaging/Configuration/MessageConfiguration.cs, src/AWS.Messaging/Properties/AssemblyInfo.cs, src/AWS.Messaging/Serialization/EnvelopeSerializer.cs, src/AWS.Messaging/Services/DnsManager.cs, src/AWS.Messaging/Services/EC2InstanceMetadataManager.cs, src/AWS.Messaging/Services/ECSContainerMetadataManager.cs, src/AWS.Messaging/Services/EnvironmentManager.cs, src/AWS.Messaging/Services/IDnsManager.cs, src/AWS.Messaging/Services/IEC2InstanceMetadataManager.cs, src/AWS.Messaging/Services/IECSContainerMetadataManager.cs, src/AWS.Messaging/Services/IEnvironmentManager.cs, src/AWS.Messaging/Services/IMessageSourceHandler.cs, src/AWS.Messaging/Services/MessageSourceHandler.cs, test/AWS.Messaging.IntegrationTests/EventBridgePublisherTests.cs, test/AWS.Messaging.IntegrationTests/SNSPublisherTests.cs, test/AWS.Messaging.IntegrationTests/SQSPublisherTests.cs, test/AWS.Messaging.IntegrationTests/SubscriberTests.cs, test/AWS.Messaging.UnitTests/MessageSourceHandlerTests.cs, test/AWS.Messaging.UnitTests/SerializationTests/EnvelopeSerializerTests.cs
DOTNET-6903
* Added the ability for users to configure the message source in the message bus
* If a value is not configured, the source will be computed based on the compute environment the process is running in.
* Added a design doc that explains the behavior implemented in this PR.
=> feat: add ability to configure message source or compute it as a fallback

src/AWS.Messaging/Configuration/MessageBusBuilder.cs, src/AWS.Messaging/Services/HandlerInvoker.cs, test/AWS.Messaging.UnitTests/HandlerInvokerTests.cs, test/AWS.Messaging.UnitTests/MessageHandlers/Handlers.cs, test/AWS.Messaging.UnitTests/Models/Models.cs
DOTNET-6957, https://github.com/awslabs/aws-dotnet-messaging/issues/46
This PR registers message handlers as scoped dependencies in the service collection.
=> chore: Register message handlers as scoped dependencies in the service collection

docs/design/telemetry-design.md, src/AWS.Messaging/Configuration/MessageBusBuilder.cs, src/AWS.Messaging/Telemetry/CompositeTelemetryTrace.cs, src/AWS.Messaging/Telemetry/DefaultTelemetryFactory.cs, src/AWS.Messaging/Telemetry/ITelemetryFactory.cs, src/AWS.Messaging/Telemetry/ITelemetryProvider.cs, src/AWS.Messaging/Telemetry/ITelemetryTrace.cs
A design for telemetry used by consumers of the library to understand how messages are being handled through their messaging system.
The PR also includes the core service level interfaces that are described in the design doc.
=> Add telemetry design doc and core service level telemetry interfaces

sampleapps/LambdaMessaging/Startup.cs, sampleapps/PublisherAPI/Program.cs, sampleapps/PublisherAPI/appsettings.json, sampleapps/SubscriberService/Program.cs, sampleapps/SubscriberService/appsettings.json
*Description of changes:* Currently the sample applications all define their own message POCOs, and do not use message identifiers so the framework is using the namespace and class names. These do not match across the sample applications, so the subscribers fail to deserialize the messages from the publishers.
This adds message identifiers so the sample applications work out of the box once you plug in your own queue URLs.
Alternatively we can move the message POCOs to a "SharedModels" assembly, let me know if you'd rather see that.
I also added the same JSON options to the subscriber that we're using on the publisher.
=> chore: Use same message identifiers across sample applications

sampleapps/PublisherAPI/Controllers/PublisherController.cs, sampleapps/PublisherAPI/Models/BidInfo.cs, sampleapps/PublisherAPI/Models/TransactionInfo.cs, sampleapps/PublisherAPI/Program.cs, sampleapps/PublisherAPI/appsettings.json, src/AWS.Messaging/Exceptions.cs, src/AWS.Messaging/Publishers/SNS/SNSPublisher.cs, src/AWS.Messaging/Publishers/SQS/SQSPublisher.cs, test/AWS.Messaging.UnitTests/MessagePublisherTests.cs
DOTNET-7234
This PR throws an exception when a message group ID is not specified while publishing to FIFO queues/topics.
=> chore: Throw an exception when a message group ID is not specified while publishing to FIFO queues/topics

src/AWS.Messaging.Lambda/AWS.Messaging.Lambda.csproj, src/AWS.Messaging.Lambda/DefaultLambdaMessaging.cs, src/AWS.Messaging/AWS.Messaging.csproj, src/AWS.Messaging/Services/DefaultMessageManager.cs
We were not being consistent with the casing of the log parameters in the library. I enabled the code analyzer as an error when not using Pascal casing and then updated all of the areas where we were not using Pascal casing.
@ashovlin You should add the `<WarningsAsErrors>CA1727</WarningsAsErrors>` to your PR for the OTel provider.
=> Make sure all logging calls use Pascal casing

AWS.Messaging.sln, sampleapps/PublisherAPI/Program.cs, sampleapps/PublisherAPI/PublisherAPI.csproj, sampleapps/SubscriberService/Program.cs, sampleapps/SubscriberService/SubscriberService.csproj, src/AWS.Messaging.Telemetry.OpenTelemetry/AWS.Messaging.Telemetry.OpenTelemetry.csproj, src/AWS.Messaging.Telemetry.OpenTelemetry/Constants.cs, src/AWS.Messaging.Telemetry.OpenTelemetry/OpenTelemetryProvider.cs, src/AWS.Messaging.Telemetry.OpenTelemetry/OpenTelemetryTrace.cs, src/AWS.Messaging.Telemetry.OpenTelemetry/README.md, src/AWS.Messaging.Telemetry.OpenTelemetry/TracerProviderBuilderExtensions.cs, src/AWS.Messaging/Configuration/AWSClientProvider.cs, src/AWS.Messaging/MessageEnvelope.cs, src/AWS.Messaging/Serialization/EnvelopeSerializer.cs, src/AWS.Messaging/Services/HandlerInvoker.cs, src/AWS.Messaging/Telemetry/TelemetryKeys.cs, test/AWS.Messaging.UnitTests/AWS.Messaging.UnitTests.csproj, test/AWS.Messaging.UnitTests/OpenTelemetryTests.cs, test/AWS.Messaging.UnitTests/SerializationTests/EnvelopeSerializerTests.cs
*Issue #, if available:* DOTNET-7031
* Adds `AWS.Messaging.Telemetry.OpenTelemetry`, which instruments the AWS Message Processing Framework for .NET for OpenTelemetry
* Based heavily on @normj 's prototype in https://github.com/awslabs/aws-dotnet-messaging/tree/normj/telemetry
* Outside of OTel, the framework will now serialize `MessageEnvelope.Metadata` as top-level properties in the JSON envelope when sending messages. We're using this to telemetry, but us and customers can use for other CloudEvents extensions and/or custom attributes.
=> feat: Add OpenTelemetry Instrumentation Provider

test/AWS.Messaging.IntegrationTests/LambdaTests.cs
*Issue #, if available:* N/A, follow-up to #71
*Description of changes:* @96malhar pointed out that the new Lambda FIFO integration test failed on his PR #77. Ran them continually locally, and saw failures in the 5-10 iteration range.
I'm now able to get to 10 iterations without failures (at which point I stopped) with these changes:
* For the FIFO messages logged to CloudWatch by the Lambda, we sort based on `Timestamp` instead of `IngestionTime`. I believe that is more accurate for when the Lambda function handled the message.
* Increased the period we're waiting for the logs from 15 to 20 seconds. Saw an iteration where there were 0 messages in the logs at the point we tried to assert them.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> Harden Lambda FIFO integration tests.

src/AWS.Messaging.Lambda/AWS.Messaging.Lambda.csproj, src/AWS.Messaging.Telemetry.OpenTelemetry/AWS.Messaging.Telemetry.OpenTelemetry.csproj, src/AWS.Messaging/AWS.Messaging.csproj
This PR adds the `beta` suffix to the package version numbers. NuGet treats any version number suffix to denote a pre-release version and also reflects the same on the package homepage. 
Example - https://www.nuget.org/packages/Amazon.Lambda.Annotations/0.10.0-preview
See [here](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#pre-release-versions) to read more about pre-release versioning.
=> chore: Add beta suffix to the package version numbers

sampleapps/LambdaMessaging/LambdaMessaging.csproj, sampleapps/LambdaMessaging/serverless.template, sampleapps/PublisherAPI/PublisherAPI.csproj, sampleapps/SubscriberService/SubscriberService.csproj, src/AWS.Messaging.Lambda/AWS.Messaging.Lambda.csproj, src/AWS.Messaging/AWS.Messaging.csproj, test/AWS.Messaging.IntegrationTests/AWS.Messaging.IntegrationTests.csproj, test/AWS.Messaging.Tests.Common/AWS.Messaging.Tests.Common.csproj, test/AWS.Messaging.Tests.Common/AWSUtilities.cs, test/AWS.Messaging.Tests.LambdaFunctions/AWS.Messaging.Tests.LambdaFunctions.csproj, test/AWS.Messaging.UnitTests/AWS.Messaging.UnitTests.csproj, test/AWS.Messaging.UnitTests/MessageBusBuilderTests.cs, test/AWS.Messaging.UnitTests/SerializationTests/EnvelopeSerializerTests.cs
1. Update all NuGet package references to their latest versions
2. Added unit tests that assert the following:
* Exceptions are thrown while creating a `MessageEnvelope` if `PublisherMapping` or `SubscriberMapping` are missing.
* An exception is thrown when configuring Lambda message processor with invalid options.
=> chore: Add additional unit tests and update project dependencies

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature-request.yml
*Description of changes:* Adds the standard issue templates we use across our repositories.
=> chore: Add GitHub issue templates

.github/workflows/BuildandTest.yml, .github/workflows/aws-ci.yml, .github/workflows/doc-site.yml, AWS.Messaging.sln, buildtools/ci.buildspec.yml, test/AWS.Messaging.Benchmarks/AWS.Messaging.Benchmarks.csproj, test/AWS.Messaging.Benchmarks/BenchmarkCollector.cs, test/AWS.Messaging.Benchmarks/BenchmarkMessage.cs, test/AWS.Messaging.Benchmarks/BenchmarkMessageHandler.cs, test/AWS.Messaging.Benchmarks/Program.cs, test/AWS.Messaging.Benchmarks/Properties/launchSettings.json
*Issue #, if available:* DOTNET-7181
Adds a console application that collects some performance benchmarks for both SQS publishing and the SQS poller.
Inspired by (and grateful for) a similar technique in https://github.com/MassTransit/MassTransit-Benchmark/ and
https://github.com/justeattakeaway/JustSaying/tree/main/tests/JustSaying.Benchmark
To run in Visual Studio, replace the queue URL in `launchSettings.json` with an actual one and press play. 
=> Initial Benchmark Application

.github/workflows/aws-ci.yml
*Description of changes:* Noticed while working on #93 that this command began failing, see https://github.com/awslabs/aws-dotnet-messaging/actions/runs/7787985228/job/21236683689 for an example.
Not sure what changed in the image or the CLI, but this seems to fix it.
=> ci: Fix escaping of payload for Lambda that selects test running account

README.md, sampleapps/PublisherAPI/Program.cs, sampleapps/PublisherAPI/appsettings.json, sampleapps/SubscriberService/Program.cs, src/AWS.Messaging/Configuration/IMessageBusBuilder.cs, src/AWS.Messaging/Configuration/IMessageConfiguration.cs, src/AWS.Messaging/Configuration/Internal/ApplicationSettings.cs, src/AWS.Messaging/Configuration/MessageBusBuilder.cs, src/AWS.Messaging/Configuration/MessageConfiguration.cs, src/AWS.Messaging/Serialization/EnvelopeSerializer.cs, src/AWS.Messaging/Serialization/MessageSerializer.cs, test/AWS.Messaging.UnitTests/SerializationTests/EnvelopeSerializerTests.cs, test/AWS.Messaging.UnitTests/SerializationTests/MessageSerializerTests.cs
DOTNET-7340
DOTNET-7342
* Added a new method `EnableDataMessageLogging` in the message bus builder that would enable data messages to be logged as well as appear in any exceptions thrown.
* Added tests, updated the sample apps and README
=> feat: add ability for users to enable data message logging

src/AWS.Messaging/Configuration/AWSClientProvider.cs, src/AWS.Messaging/Configuration/EventBridgePublisherConfiguration.cs, src/AWS.Messaging/Configuration/IMessageBusBuilder.cs, src/AWS.Messaging/Configuration/IMessagePublisherConfiguration.cs, src/AWS.Messaging/Configuration/MessageBusBuilder.cs, src/AWS.Messaging/Configuration/SNSPublisherConfiguration.cs, src/AWS.Messaging/Configuration/SQSPublisherConfiguration.cs, src/AWS.Messaging/Publishers/EventBridge/EventBridgeOptions.cs, src/AWS.Messaging/Publishers/EventBridge/EventBridgePublisher.cs, src/AWS.Messaging/Publishers/SNS/SNSOptions.cs, src/AWS.Messaging/Publishers/SNS/SNSPublisher.cs, src/AWS.Messaging/Publishers/SQS/SQSOptions.cs, src/AWS.Messaging/Publishers/SQS/SQSPublisher.cs, test/AWS.Messaging.UnitTests/AppSettingsConfigurationTests.cs, test/AWS.Messaging.UnitTests/MessagePublisherTests.cs
*Issue #, if available:* https://github.com/awslabs/aws-dotnet-messaging/issues/90, DOTNET-7333
*Description of changes:* This adds support for configuring the destination and AWS client at the point of publishing. This may be useful for multi-tenant applications as described in #90 , where the destination of the message (and therefore the credentials required to publish it) aren't known until building the message.
For configuring the publisher without a destination in advance, I considered:
1. A new method, like `AddGenericSQSPublisher`, (or maybe `Destinationless`? `Unknown`?) 
* **Why not?** Couldn't think of a good name
2. Leaving the signature as is, but requiring users to register a fake destination `AddSQSPublisher("WILL_OVERRIDE_LATER")`
* **Why not?** Don't want to end up in a …
=> feat: Add support for specifying the message destination and AWS service client when publishing a specific message.

src/AWS.Messaging/Configuration/Internal/TaskMetadataResponse.cs, src/AWS.Messaging/Services/ECSContainerMetadataManager.cs, src/AWS.Messaging/Services/IECSContainerMetadataManager.cs, src/AWS.Messaging/Services/MessageSourceHandler.cs, test/AWS.Messaging.UnitTests/ECSContainerMetadataManagerTests.cs, test/AWS.Messaging.UnitTests/MessageSourceHandlerTests.cs
DOTNET-7341
* Added validation for the ECS Metadata endpoint to look for the IP `169.254.170.2`
* Added a POCO that represents the data returned by the endpoint which adds more validation on the structure of the data
* Added validation to the Cluster and TaskARN returned
=> chore: add validation to the ECS Task Metadata

README.md, docs/docs/getting-started.md, sampleapps/PublisherAPI/Controllers/PublisherController.cs, src/AWS.Messaging/Publishers/EventBridge/IEventBridgePublisher.cs, src/AWS.Messaging/Publishers/MessageRoutingPublisher.cs, src/AWS.Messaging/Publishers/SNS/ISNSPublisher.cs, src/AWS.Messaging/Publishers/SQS/ISQSPublisher.cs, src/AWS.Messaging/Publishers/SQS/SQSPublisher.cs, src/AWS.Messaging/Services/ICommandPublisher.cs, src/AWS.Messaging/Services/IEventPublisher.cs, test/AWS.Messaging.Benchmarks/Program.cs, test/AWS.Messaging.IntegrationTests/FifoSubscriberTests.cs, test/AWS.Messaging.IntegrationTests/LambdaTests.cs, test/AWS.Messaging.UnitTests/MessagePublisherTests.cs, test/AWS.Messaging.UnitTests/OpenTelemetryTests.cs
DOTNET-7370, #89 
* Add `ICommandPublisher` and `IEventPublisher` to represent publishers that send to specific recipients and publishers that publish to unknown recipients. This was needed to allow extending publishers in the future and adding more of them. A command publisher has a `SendAsync` while an event publisher has a `PublishAsync`.
* Updated tests, sample apps and docs.
=> chore: follow design patterns for publishers

src/AWS.Messaging/Configuration/MessageBusBuilder.cs, src/AWS.Messaging/Configuration/SQSMessagePollerConfiguration.cs, src/AWS.Messaging/Configuration/SQSMessagePollerOptions.cs, src/AWS.Messaging/SQS/SQSMessagePoller.cs, test/AWS.Messaging.UnitTests/SQSMessagePollerTests.cs
*Issue #, if available:* DOTNET-6819
1. **BREAKING CHANGE**: Replaces `IsSQSExceptionFatal` with a more generic `IsExceptionFatal` to let users categorize non-SQS exceptions too.
* I think the increased flexibility is worth the breaking change while we're still in preview, but let me know if you disagree.
2. Expands the list of exceptions derived from `AmazonSQSException` that we treat as fatal.
3. Classifies some of our own `AWSMessagingExceptions` as fatal.
My philosophy when classifying exceptions was:
* Anything that would likely always be unsuccessful should be fatal (e.g. invalid queue URL, inadequate permissions, invalid framework configuration)
* Anything either temporary (e.g. throttling) or on a per-message basis (e.g. deserialization) are non-fatal. …
=> Refine list of fatal exceptions when polling SQS

README.md, sampleapps/PublisherAPI/Controllers/PublisherController.cs, src/AWS.Messaging/IMessagePublisher.cs
*Issue #, if available:* #61, DOTNET-7334
*Description of changes:* This expands the documentation, examples, and README content for `IMessagePublisher` to clarify that it can be used to publish multiple message types to multiple services.
=> docs: Improve documentation and examples around IMessagePublisher

docs/docfx.json
After the PR #102, GitHub Pages and the API reference stopped being rendered properly. This PR fixes the issue which was not reproducible locally.
=> fix: fix the API reference not rendering

src/AWS.Messaging.Lambda/AWS.Messaging.Lambda.csproj, src/AWS.Messaging.Telemetry.OpenTelemetry/AWS.Messaging.Telemetry.OpenTelemetry.csproj, src/AWS.Messaging/AWS.Messaging.csproj
DOTNET-6926
Added the properties required for SourceLink as well as the proper package reference. Once the projects are packed using `dotnet pack`, a symbols file will be generated alongside the NuGet package. In our pipelines, when we do a `nuget push`, if there is a symbols package in the same directory as the NuGet package, then the symbols package will automatically be uploaded.
=> chore: add SourceLink to project files

src/AWS.Messaging/Serialization/EnvelopeSerializer.cs, test/AWS.Messaging.IntegrationTests/EventBridgeEndToEndTests.cs, test/AWS.Messaging.IntegrationTests/SNSEndToEndTests.cs, test/AWS.Messaging.UnitTests/SerializationTests/EnvelopeSerializerTests.cs
*Issue*
* https://github.com/awslabs/aws-dotnet-messaging/issues/97
* DOTNET-7432
*Description of changes:* 
This is a sample SQS message when messages are forwarded by EventBridge
```
{
"version": "0",
"id": "961ac8a3-a4ee-0e17-d8d9-36c81ae29955",
"detail-type": "AWS.Messaging.IntegrationTests.Models.ChatMessage",
"source": "/aws/messaging",
"account": "000000000",
"time": "2024-03-25T20:39:11Z",
"region": "us-west-2",
"resources": [],
"detail": {
"id": "526d5466-5f51-42ce-a64b-8a220a7f1b71",
"source": "/aws/messaging",
"specversion": "1.0",
"type": "AWS.Messaging.IntegrationTests.Models.ChatMessage",
"time": "2024-03-25T20:39:10.8491344+00:00",
"data": "{\"MessageDescription\":\"Test1\"}"
}
}
```
The `detail` property is sent as a JSON object and not as a string. Invoking …
=> fix: Correctly deserialize outer envelope when processing messages relayed through EventBridge

.autover/autover.json, .github/workflows/create-release-pr.yml, .github/workflows/sync-main-dev.yml, CHANGELOG.md, src/AWS.Messaging.Lambda/AWS.Messaging.Lambda.csproj, src/AWS.Messaging.Telemetry.OpenTelemetry/AWS.Messaging.Telemetry.OpenTelemetry.csproj, src/AWS.Messaging/AWS.Messaging.csproj
This PR adds support for AutoVer which automates versioning based on `change file` which contributors add to their PRs/Branches to indicate the type of change they are performing as well as the changelog message.
The change file looks like:
```
{
"Projects": [
{
"Name": "AWS.Messaging",
"Type": "Patch",
"ChangelogMessages": [
"The changelog message"
]
}
]
}
```
As part of the normal SDLC on this repo, when we are ready to release a set of changes, we can kick off the `Create Release PR` workflow against the `dev` branch. This workflow will go through the `change file` and determine the proper version for the projects that need to be versioned. It will also create the changelog based on the messages in the `change files`. These file changes will be added to a new …
=> ci: add support for automated versioning and changelog creation

.github/workflows/create-release-pr.yml, .github/workflows/sync-main-dev.yml
* Updates the release workflows to use a PAT for the GitHub Automation User
* Fix the current release workflow which fails when merging `dev` to `main` due to our branch protection rules. 
* Fix the Release PR which currently doesn't run PR checks
Note: the 2 repository secrets `RELEASE_WORKFLOW_ACCESS_TOKEN_ROLE_ARN` and `RELEASE_WORKFLOW_ACCESS_TOKEN_NAME` have not yet been created. They will be created once we update the release infra.
=> chore: update release workflows to use a PAT

.autover/changes/c2f71984-1524-4dde-8692-d6f965d6ebc0.json, src/AWS.Messaging/Exceptions.cs, src/AWS.Messaging/IMessagePublisher.cs, src/AWS.Messaging/Publishers/EventBridge/EventBridgePublishResponse.cs, src/AWS.Messaging/Publishers/EventBridge/EventBridgePublisher.cs, src/AWS.Messaging/Publishers/EventBridge/IEventBridgePublisher.cs, src/AWS.Messaging/Publishers/IPublishResponse.cs, src/AWS.Messaging/Publishers/MessageRoutingPublisher.cs, src/AWS.Messaging/Publishers/SNS/ISNSPublisher.cs, src/AWS.Messaging/Publishers/SNS/SNSPublishResponse.cs, src/AWS.Messaging/Publishers/SNS/SNSPublisher.cs, src/AWS.Messaging/Publishers/SQS/ISQSPublisher.cs, src/AWS.Messaging/Publishers/SQS/SQSPublisher.cs, src/AWS.Messaging/Publishers/SQS/SQSSendResponse.cs, src/AWS.Messaging/Services/ICommandPublisher.cs, src/AWS.Messaging/Services/IEventPublisher.cs, test/AWS.Messaging.UnitTests/MessagePublisherTests.cs, test/AWS.Messaging.UnitTests/OpenTelemetryTests.cs
When a message fails from eventbridge, the error result was not shown. This could lead to some issues in the future. 
I adapted this so the errormessage and if required the errorcode can be retrieved 
As the publisher is abstracted across EventBridge, SQS and SNS I had to make some sacrifices for naming; event <-> message. 
Please have a look at it and provide some feedback so it can be adapted where you need it. 
=> return the result from the publisher to the caller.

.github/workflows/closed-issue-message.yml, .github/workflows/handle-stale-discussions.yml, .github/workflows/stale_issues.yml
Added GitHub workflows for stale issue/discussions and closed issue message. These were somehow missing from this repository.
___
=> chore: Add GitHub workflows for stale issue/discussions and closed issue message.

.autover/changes/237dcfa7-055f-4342-8633-de16951d29c2.json, src/AWS.Messaging.Lambda/DefaultLambdaMessaging.cs, src/AWS.Messaging.Lambda/LambdaMessagingOptions.cs, src/AWS.Messaging.Lambda/Services/DefaultLambdaMessageProcessor.cs, src/AWS.Messaging.Lambda/Services/LambdaMessageProcessorConfiguration.cs, test/AWS.Messaging.UnitTests/LambdaTests.cs
Issue #150
Adds a configuration option to [LambdaMessagingOptions](https://github.com/awslabs/aws-dotnet-messaging/blob/main/src/AWS.Messaging.Lambda/LambdaMessagingOptions.cs) for a `VisibilityTimeout` value when there are partial batch failures. In that scenario, the failed messages will have their message visibility set to this default value.
Prior to this change, the message visibility would not be set/changed. Which, if you were using a FIFO queue, would mean that other messages in that message group would be blocked until the original message visibility timeout occurred, which could be a while.
After this change, the message visibility will be changed on failure.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
=> Add configurable visibility timeout default when using partial batch failures

.autover/changes/7affc078-3e1b-4baa-a27b-67280b0e95d5.json, src/AWS.Messaging/Configuration/MessageBusBuilder.cs, test/AWS.Messaging.UnitTests/MessageBusBuilderTests.cs
This is a way to support multiple invocations of AddAWSMessageBus against same ServiceCollection with the least amount of changes.
Submitting for feedback. Possible you may want to take a different approach.
Issue #152
Change `MessageConfiguration` to a static, so it can be shared across implementations. 
Add unit test for scenario and fix unit test scaffold to support setting up new `MessageConfiguration` contexts for each test.
=> Use static MessageConfiguration tied to ServiceCollection

.autover/changes/1cc6641e-f4c6-4db6-b480-cb3d96fdaab7.json, src/AWS.Messaging/Publishers/EventBridge/IEventBridgePublisher.cs
Hi, thanks for the library it's been a huge help. Just noticed that the EventBridge publisher was referencing SNS instead of EventBridge.
=> Removes references to SNS in EventBridge publisher

.autover/changes/477dcfa7-055f-4342-8633-de16951d29c1.json, src/AWS.Messaging.Lambda/AWS.Messaging.Lambda.csproj, src/AWS.Messaging.Lambda/Services/DefaultLambdaMessageProcessor.cs, src/AWS.Messaging.Telemetry.OpenTelemetry/AWS.Messaging.Telemetry.OpenTelemetry.csproj, src/AWS.Messaging/AWS.Messaging.csproj, src/AWS.Messaging/SQS/SQSMessagePoller.cs, src/AWS.Messaging/Serialization/EnvelopeSerializer.cs, test/AWS.Messaging.IntegrationTests/AWS.Messaging.IntegrationTests.csproj, test/AWS.Messaging.Tests.Common/AWS.Messaging.Tests.Common.csproj, test/AWS.Messaging.UnitTests/MessagePublisherTests.cs, test/AWS.Messaging.UnitTests/SerializationTests/EnvelopeSerializerTests.cs
DOTNET-7762
This PR updates the .NET SDK dependencies to the latest version 4.0.0-preview.4
=> feat: add support for .NET SDK V4

.autover/changes/cddcba75-9039-4f3c-967c-72841ed2af9d.json, src/AWS.Messaging/SQS/SQSMessagePoller.cs
When an app gets shut down, the CancellationToken passed in the BackgroundService gets cancelled. When that happens, the SQS poller throws an exception, which gets logged as an error. This means a consuming app logs error + warning every time the app shuts down. This change catches the exception and returns empty list of messages, so the app can gracefully shut down without any errors being logged.
Logs from sampleapps/SubscriberService before the change:
```console
info: AWS.Messaging.Services.MessagePumpService[0]
Starting polling: <queue url>
info: Microsoft.Hosting.Lifetime[0]
Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0] …
```
=> Avoid logging errors during shutdown due to SQS client call being cancelled

.autover/changes/0529a49e-6b48-4eea-874b-1a5c2be8b029.json, .github/workflows/BuildandTest.yml, src/AWS.Messaging/Services/DefaultMessageManager.cs, test/AWS.Messaging.UnitTests/LambdaTests.cs
https://github.com/awslabs/aws-dotnet-messaging/issues/174
While processing messages in Lambda if we get a failure in a message group we skip processing the remaining messages. We should be reporting to Lambda as part of the SQSBatchResponse the items we skipped as failures so Lambda doesn't think they were successfully processed.
=> Fix issue with fifo queues message failure reporint issue

.autover/changes/01370ae5-3537-4723-80b3-ee82e79e80b9.json, src/AWS.Messaging/Serialization/EnvelopeSerializer.cs, test/AWS.Messaging.IntegrationTests/FifoSubscriberTests.cs, test/AWS.Messaging.IntegrationTests/SubscriberTests.cs, test/AWS.Messaging.UnitTests/SerializationTests/EnvelopeSerializerTests.cs
*Issue #, if available:* DOTNET-7438
1. Update error message when subscriber mapping is null.
2. I was trying to reproduce the other bugs mentioned in above ticket, but was not able to, so I am just updating the error message for now
Example error message
```
{
"errorType": "FailedToCreateMessageEnvelopeException",
"errorMessage": "Failed to create MessageEnvelope",
"stackTrace": [
"at AWS.Messaging.Serialization.EnvelopeSerializer.ConvertToEnvelopeAsync(Message sqsMessage) in C:\\dev\\repos\\aws-dotnet-messaging\\src\\AWS.Messaging\\Serialization\\EnvelopeSerializer.cs:line 192",
"at AWS.Messaging.Lambda.Services.DefaultLambdaMessageProcessor.ProcessMessagesAsync(CancellationToken token) in C:\\dev\\repos\\aws-dotnet-messaging\\src\\AWS.Messaging.Lambda\\Services …
```
=> Update error message for when subscribermapping is null

.autover/changes/d7e286d4-e36f-48e9-b6b0-db5ddb200bfa.json, sampleapps/LambdaMessaging/LambdaMessaging.csproj, sampleapps/LambdaMessaging/serverless.template, src/AWS.Messaging.Lambda/AWS.Messaging.Lambda.csproj, src/AWS.Messaging.Telemetry.OpenTelemetry/AWS.Messaging.Telemetry.OpenTelemetry.csproj, src/AWS.Messaging/AWS.Messaging.csproj, test/AWS.Messaging.Tests.LambdaFunctions/AWS.Messaging.Tests.LambdaFunctions.csproj
Since we will only be releasing this library with support for .NET SDK V4, I am reverting the version numbers to match what we currently have on `main`.  Previously, we were planning on releasing a `2.0.0` version for the V4 SDK upgrade which is no longer the case.
=> chore: revert version numbers to match main branch

.autover/changes/01370ae5-3537-4723-80b3-ee82e79e80b9.json, .github/workflows/doc-site.yml, CHANGELOG.md, sampleapps/LambdaMessaging/HandlerSampleRequest.json, sampleapps/LambdaMessaging/LambdaMessaging.csproj, sampleapps/LambdaMessaging/Properties/launchSettings.json, sampleapps/LambdaMessaging/README.md, sampleapps/LambdaMessaging/Startup.cs, sampleapps/PollyIntegration/PollyIntegration.csproj, sampleapps/PollyIntegration/README.md, sampleapps/PublisherAPI/PublisherAPI.csproj, sampleapps/PublisherAPI/README.md, sampleapps/README.md, sampleapps/SubscriberService/README.md, sampleapps/SubscriberService/SubscriberService.csproj, src/AWS.Messaging.Lambda/README.md, src/AWS.Messaging/Serialization/EnvelopeSerializer.cs, test/AWS.Messaging.IntegrationTests/FifoSubscriberTests.cs, test/AWS.Messaging.IntegrationTests/SubscriberTests.cs, test/AWS.Messaging.UnitTests/SerializationTests/EnvelopeSerializerTests.cs
*Description of changes:* sync dev to v4
=> sync dev to v4

.autover/changes/276cbae4-0a14-4efa-9fd2-760cf4529b0a.json, sampleapps/SubscriberService/Program.cs, src/AWS.Messaging/Configuration/IMessageBusBuilder.cs, src/AWS.Messaging/Configuration/IMessageConfiguration.cs, src/AWS.Messaging/Configuration/MessageBusBuilder.cs, src/AWS.Messaging/Configuration/MessageConfiguration.cs, src/AWS.Messaging/Configuration/PollingControlToken.cs, src/AWS.Messaging/SQS/SQSMessagePoller.cs, test/AWS.Messaging.IntegrationTests/SubscriberTests.cs, test/AWS.Messaging.UnitTests/MessagePublisherTests.cs, test/AWS.Messaging.UnitTests/SQSMessagePollerTests.cs
Fixing test issues with customer PR https://github.com/awslabs/aws-dotnet-messaging/pull/179 and rebasing on top of `v4sdk-development` branch.
Fixes https://github.com/awslabs/aws-dotnet-messaging/issues/147
=> Issue-147: Add feature to pause/resume SQSMessagePoller

.autover/changes/56a61b2c-4302-4077-9dc6-3fc3bc60a998.json, src/AWS.Messaging/AWS.Messaging.csproj, src/AWS.Messaging/MessageEnvelope.cs, src/AWS.Messaging/Serialization/EnvelopeSerializer.cs, src/AWS.Messaging/Serialization/IMessageSerializer.cs, src/AWS.Messaging/Serialization/MessageSerializer.cs, src/AWS.Messaging/Serialization/MessageSerializerResults.cs, test/AWS.Messaging.IntegrationTests/EventBridgePublisherTests.cs, test/AWS.Messaging.IntegrationTests/SNSPublisherTests.cs, test/AWS.Messaging.IntegrationTests/SQSPublisherTests.cs, test/AWS.Messaging.UnitTests/MessageHandlers/Handlers.cs, test/AWS.Messaging.UnitTests/SerializationTests/EnvelopeSerializerTests.cs, test/AWS.Messaging.UnitTests/SerializationTests/MessageSerializerTests.cs
*Issue #, if available:* https://github.com/awslabs/aws-dotnet-messaging/issues/168
1. Updates the `MessageSerializer` to store the json value as the actual json object in the `data` field. 
2. Add `datacontenttype` field to message
**Before**
```
{
"version": "0",
"id": "359472c2-c66b-00df-5976-cef04c383a15",
"detail-type": "Payload",
"source": "/aws/messaging",
"account": "147997163238",
"time": "2025-03-14T18:40:58Z",
"region": "us-east-1",
"resources": [],
"detail": {
"id": "fdc50c90-f747-4794-ae91-d39894cc6442",
"source": "/aws/messaging",
"specversion": "1.0",
"type": "Payload",
"time": "2025-03-14T18:40:56.3356898+00:00",
"data": "{\"Id\":\"8b939477-089c-49ce-ae90-49e9817bd593\",\"Name\":\"Test\",\"SomeValue\":42}"
}
```
**After**
```
{
"version": "0", …
```
=> Updates the `MessageSerializer` to store the json value as the actual json object in the `data` field.Update data field serialization

.autover/changes/81b0f05a-0e00-4c87-8bff-1d709e1b6e20.json, src/AWS.Messaging/Services/DefaultMessageManager.cs, test/AWS.Messaging.UnitTests/DefaultMessageManagerTests.cs
Fixes an issue in where failed FIFO queue message groups cause visibility timeout extensions errors. When a message in a group failed processing, subsequent messages remained in `_inFlightMessageMetadata` with stale receipt handles. These stale entries accumulated alongside new entries when messages were repolled, causing perpetual failed attempts to extend visibility timeouts after the SQS 12 hour maximum extension window was reached.
DOTNET-8035
In long-running processes using FIFO queues:
- When a message in a group failed, subsequent messages were correctly skipped but remained in metadata
- System continued trying to extend visibility timeouts using _outdated receipt handles_
- When messages were repolled, new entries were added to metadata while stale entries remained
- The …
=> Remove stale entries from inflight message metadata. Fixes #191

.autover/changes/261d1081-4809-42df-afde-5541c4c1e3f2.json, src/AWS.Messaging/SQS/SQSMessagePoller.cs
When we poll SQS and no messages are received, `messages` is `null` but we are still trying to access the count anyway. This adds a check to ensure its not null
=> Fix null reference exception

AWS.Messaging.sln, sampleapps/AppHost/AppHost.csproj, sampleapps/AppHost/Program.cs, sampleapps/AppHost/Properties/launchSettings.json, sampleapps/AppHost/README.md, sampleapps/AppHost/app-resources.template, sampleapps/AppHost/appsettings.Development.json, sampleapps/AppHost/appsettings.json, sampleapps/LambdaMessaging/Properties/launchSettings.json, sampleapps/LambdaMessaging/README.md, sampleapps/PollyIntegration/Program.cs, sampleapps/PollyIntegration/README.md, sampleapps/PublisherAPI/Program.cs, sampleapps/PublisherAPI/README.md, sampleapps/README.md, sampleapps/SubscriberService/Program.cs, sampleapps/SubscriberService/README.md
*Issue #, if available:* DOTNET-8037
1. Update sample apps to use .NET aspire
2. This change adds all sample apps as projects to Aspire. It allows the user to easily test everything easily.
3. It also automatically creates all the required cloudformation/SQS/SNS queues
The basic end to end flow that the user can do is 2 scenarios.
1. Lambda Messaging - Uses aspire + test tool to allow user to try out lambda messaging functionality
2. Publisher + Subscriber. The user can use the PublisherAPI project to publish `ChatMessage`s and then the associated `SubscriberService` will read those messages. The user can swap out the regular `SubscriberService` for the `PollyIntegration` service as well.
By submitting this pull request, I confirm that you can use, modify, copy, …
=> Update sample apps to use Aspire

.github/workflows/handle-stale-discussions.yml, test/AWS.Messaging.UnitTests/SQSMessagePollerTests.cs
=> Sync main from dev
