aws/aws-dotnet-messaging

- src/AWS.Messaging/SQS/SQSMessagePoller.cs
- test/AWS.Messaging.UnitTests/SQSMessagePollerTests.cs
*Issue #, if available:* DOTNET-6956
*Description of changes:* There's a relatively common race condition where these happen very close to each other:
1. A message handler task finishes processing a message, and deletes it.
2. The message timeout visibility extension task attempts to extend the visibility timeout of the same message, since the handler task is not entirely finished with it.
This results in an entry in `ChangeMessageVisibilityBatchResponse.Failed` collection for the message that was just deleted.
In flight messages are stored in a `ConcurrentDictionary`, but we don't lock the work after we've read from the dictionary and are preparing and then sending the `ChangeMessageVisibilityBatchRequest`.
Rather than introduce more synchronization between deletion and extensions, we're …
> fix: Only log trace messages for the case where SQSMessagePoller fails to extend a message's visibility timeout because it was recently deleted

- .gitignore
- docs/design/telemetry-design.md
- src/AWS.Messaging.Lambda/DefaultLambdaMessaging.cs
- src/AWS.Messaging.Lambda/Services/DefaultLambdaMessageProcessor.cs
- src/AWS.Messaging/Properties/AssemblyInfo.cs
- src/AWS.Messaging/Publishers/EventBridge/EventBridgePublisher.cs
- src/AWS.Messaging/Publishers/MessageRoutingPublisher.cs
- src/AWS.Messaging/Publishers/SNS/SNSPublisher.cs
- src/AWS.Messaging/Publishers/SQS/SQSPublisher.cs
- src/AWS.Messaging/Services/HandlerInvoker.cs
- src/AWS.Messaging/Telemetry/TelemetryKeys.cs
- test/AWS.Messaging.UnitTests/HandlerInvokerTests.cs
- test/AWS.Messaging.UnitTests/MessagePublisherTests.cs
DOTNET-7033
* Use the Trace method from ITelemetryFactory to start a trace
* Added exceptions to the trace via the AddException method
> feat: Instrument AWS.Message to create traces

- .github/workflows/semgrep-analysis.yml
- .semgrepignore
This PR enables code scanning via Semgrep.
Inspired by the sample GitHub action Semgrep configuration - https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/#sample-github-actions-configuration-file
Similar PR in the `aws-dotnet-deploy` repo - https://github.com/aws/aws-dotnet-deploy/pull/508
> chore: Enable code scanning via Semgrep

- README.md
This PR updates the REAMDE by specifying the default values in `SQSMessagePollerOptions`.
> docs: Update REAMDE by specifying the default values in SQSMessagePollerOptions

- CHANGELOG.md
- README.md
- docs/docs/getting-started.md
- src/AWS.Messaging.Lambda/README.md
- src/AWS.Messaging.Telemetry.OpenTelemetry/README.md
* Added initial changelog for the 3 new packages
* Updated Readme to add NuGet package badge and GitHub build status badge
> chore: release 0.1.0-beta prep

- test/AWS.Messaging.IntegrationTests/LambdaTests.cs
chore: skip Lambda tests due to intermittent issues in release pipeline
> chore: skip Lambda tests due to intermittent issues in release pipeline

- README.md
fix: Update broken link in README
> fix: Update broken link in README

- CHANGELOG.md
*Description of changes:* Updating changelog for what was released via #104 
> Update CHANGELOG.md for 0.2.0-beta

- CHANGELOG.md
- src/AWS.Messaging.Lambda/AWS.Messaging.Lambda.csproj
- src/AWS.Messaging.Telemetry.OpenTelemetry/AWS.Messaging.Telemetry.OpenTelemetry.csproj
- src/AWS.Messaging/AWS.Messaging.csproj
* Updated the following projects:
* AWS.Messaging (0.3.0-beta)
* AWS.Messaging.Lambda (0.1.1-beta)
* AWS.Messaging.Telemetry.OpenTelemetry (0.1.1-beta)
* Added the changelog for the next release
> Update projects versions and add changelog for next beta release

- .autover/changes/519a5032-f249-4598-a46e-58bba51e109e.json
- CHANGELOG.md
- README.md
- src/AWS.Messaging.Lambda/README.md
- src/AWS.Messaging.Telemetry.OpenTelemetry/README.md
* Added a change file that describes the upcoming changelog.
* Fixed the formatting of the `CHANGELOG.md` file to match the formatting used by AutoVer
* Updated Readme files to indicate the library is in dev preview instead of early release.
> chore: update README as part of release prep

- README.md
- src/AWS.Messaging.Lambda/README.md
- src/AWS.Messaging.Telemetry.OpenTelemetry/README.md
*Description of changes:* Adds link to blog post and API reference to the three READMEs.
> chore: Update links in READMEs

- .github/workflows/create-release-pr.yml
- .github/workflows/sync-main-dev.yml
- README.md
- src/AWS.Messaging.Lambda/README.md
- src/AWS.Messaging.Telemetry.OpenTelemetry/README.md
Merge Updated Workflows from #121 to main
> Merge Updated Workflows to main

- docs/docs/design/telemetry-design.md
This PR merges the branch from https://github.com/awslabs/aws-dotnet-messaging/pull/125 into the repo to allow PR checks to run.
> docs: update telemetry design wording for clarity

- .autover/changes/cb641346-f9f6-414d-be09-90ea0b8366a7.json
- cb641346-f9f6-414d-be09-90ea0b8366a7.json
- src/AWS.Messaging/AWS.Messaging.csproj
- src/AWS.Messaging/Configuration/AWSClientProvider.cs
- test/AWS.Messaging.IntegrationTests/AWS.Messaging.IntegrationTests.csproj
- test/AWS.Messaging.Tests.Common/AWS.Messaging.Tests.Common.csproj
- test/AWS.Messaging.Tests.LambdaFunctions/AWS.Messaging.Tests.LambdaFunctions.csproj
SDK-169882
chore: Update User-Agent string
*Testing*
Verified that the UA is `lib/aws-dotnet-messaging#0.9.0.0`
> [UA update] chore: Update User-Agent string

- .autover/changes/cb641346-f9f6-414d-be09-90ea0b8366a7.json
- CONTRIBUTING.md
- docs/docs/design/telemetry-design.md
- src/AWS.Messaging/AWS.Messaging.csproj
- src/AWS.Messaging/Configuration/AWSClientProvider.cs
- test/AWS.Messaging.IntegrationTests/AWS.Messaging.IntegrationTests.csproj
- test/AWS.Messaging.Tests.Common/AWS.Messaging.Tests.Common.csproj
- test/AWS.Messaging.Tests.LambdaFunctions/AWS.Messaging.Tests.LambdaFunctions.csproj
> Merge dev -> main

- docs/docfx.json
- docs/template/public/beacon_scode.js
None
Add beacon functionality to the docs website.
> add beacon to the docs site

- .github/workflows/closed-issue-message.yml
- .github/workflows/handle-stale-discussions.yml
- .github/workflows/stale_issues.yml
chore: Add GitHub workflows for stale issue/discussions and closed issue message.
___
> chore: Add GitHub workflows for stale issue/discussions and closed issue message.

- .github/workflows/doc-site.yml
* Update GitHub actions that are deprecated which were causing the doc site to not properly rended
> chore: fix doc site

- .autover/changes/eaeaef89-fa95-425c-b5d2-6e346bc5debd.json
- src/AWS.Messaging/AWS.Messaging.csproj
- test/AWS.Messaging.IntegrationTests/AWS.Messaging.IntegrationTests.csproj
- test/AWS.Messaging.Tests.Common/AWS.Messaging.Tests.Common.csproj
*Issue #, if available:* DOTNET-8029
1. Update AWS SDK to preview 11
> update AWS SDK to Preview 11

- README.md
DOTNET-7419
Update Readme with minimum IAM permissions for:
* Handling SQS messages
* Publishing to SQS
* Publishing to SNS
* Publishing to EventBridge
> docs: update Readme with minimum IAM permissions

- .autover/autover.json
- .github/workflows/create-release-pr.yml
- .github/workflows/sync-main-dev.yml
Add preview label and update autover
> Add preview label and update autover

- .github/workflows/aws-ci.yml
- .github/workflows/change-file-in-pr.yml
- .github/workflows/closed-issue-message.yml
- .github/workflows/create-release-pr.yml
- .github/workflows/doc-site.yml
- .github/workflows/handle-stale-discussions.yml
- .github/workflows/issue-regression-labeler.yml
- .github/workflows/semgrep-analysis.yml
- .github/workflows/stale_issues.yml
- .github/workflows/sync-main-dev.yml
*Issue #, if available:* DOTNET-8045
Update workflows to be pinned to sha. This is following the best practices https://www.stepsecurity.io/blog/pinning-github-actions-for-enhanced-security-a-complete-guide#:~:text=Action%20pinning%20with%20specific%20commit,point%20to%20different%20code%20versions
Created 2 scripts to update everything
```
function Convert-TagToCommit {
param (
[string]$owner,
[string]$repo,
[string]$tag
)
try {
$result = gh api "repos/$owner/$repo/git/refs/tags/$tag" | ConvertFrom-Json
return $result.object.sha
}
catch {
Write-Warning "Could not resolve tag $tag for $owner/$repo"
return $null
}
}
$workflowFiles = Get-ChildItem -Path ".github/workflows" -Filter "*.yml" -Recurse
foreach ($file in $workflowFiles) {
$content = Get-Content …
```
> update actions to use commit hash

- CHANGELOG.md
- README.md
> Sync up V3 and V4 branches

- .autover/changes/f47cf6f6-17f3-44b2-81a1-cf5bd4e228bc.json
- sampleapps/PollyIntegration/Program.cs
- sampleapps/SubscriberService/Program.cs
- src/AWS.Messaging/AWS.Messaging.csproj
- test/AWS.Messaging.IntegrationTests/AWS.Messaging.IntegrationTests.csproj
- test/AWS.Messaging.Tests.Common/AWS.Messaging.Tests.Common.csproj
- test/AWS.Messaging.Tests.Common/Services/InMemoryLogger.cs
- test/AWS.Messaging.UnitTests/DefaultMessageManagerTests.cs
- test/AWS.Messaging.UnitTests/SerializationTests/EnvelopeSerializerTests.cs
- test/AWS.Messaging.UnitTests/SerializationTests/Handlers/MessageDataHandlerTests.cs
- test/AWS.Messaging.UnitTests/SerializationTests/Parsers/SQSMessageParserTests.cs
* Update .NET SDK to v4.0.0
* Fix warnings in the solution
> chore: update .NET SDK to v4.0.0

- .autover/autover.json
- .autover/changes/f47cf6f6-17f3-44b2-81a1-cf5bd4e228bc.json
Remove preview suffix and update all packages
> remove preview suffix and update all packages

- sampleapps/SubscriberService/README.md
*Description of changes:* When i was testing another feature i tried the existing readme example and it didnt work. updating to correct format
> fix readme

- .autover/changes/0c10f111-a696-4e76-b12c-e4b4c7aedd14.json
- README.md
- src/AWS.Messaging.Lambda/README.md
- src/AWS.Messaging.Telemetry.OpenTelemetry/README.md
Prepare library for GA release
> chore: prepare GA release

- CHANGELOG.md
- src/AWS.Messaging.Telemetry.OpenTelemetry/AWS.Messaging.Telemetry.OpenTelemetry.csproj
- src/AWS.Messaging.Telemetry.OpenTelemetry/README.md
> chore: revert OTel package GA

- CHANGELOG.md
- src/AWS.Messaging.Telemetry.OpenTelemetry/AWS.Messaging.Telemetry.OpenTelemetry.csproj
- src/AWS.Messaging.Telemetry.OpenTelemetry/README.md
> Release PR

- test/AWS.Messaging.UnitTests/SQSMessagePollerTests.cs
DOTNET-8112
The test was flaky due to race conditions in verifying message receipt after restarting polling. The test relied on arbitrary wait times and mock verification timing, which could lead to intermittent failures.
- Replaced arbitrary wait times with a `TaskCompletionSource` to reliably detect when a message is actually received
- Added explicit timeout handling with a 5-second window to fail fast if no message is received
- Improved test reliability by waiting for the actual event of message receipt rather than relying on timing-based verification
- Verified test stability through multiple runs
- https://github.com/aws/aws-dotnet-messaging/actions/runs/15512751260 (has multiple runs)
- https://github.com/aws/aws-dotnet-messaging/actions/runs/15512598937
By submitting this pull …
> Fix flaky SQSMessagePoller_PollingControlRestarted_PollsSQS test
